### ISSUE TITLE
:synchronize option broken in Rails 6.0.0.RC1

### ISSUE THREAD

**Issue by bill-filler** [zdennis/activerecord-import#622]
Testing activerecord-import 1.0.1 with Rails 6.0.0.rc1
On Rails 5, this code was working:
`Category.import(new_categories, :validate => false, :recursive => true, :synchronize => new_categories)`

On Rails 6 I get the following error:
```
NoMethodError (undefined method `clear_aggregation_cache' for #<Category:0x000055877a5acf10>
Did you mean?  clear_association_cache):
```

Looking at Rails code, looks like `clear_aggregation_cache` and `clear_association_cache` have been made private and replaced by public `reload` method. Assuming activerecord-import would need to be changed to use `reload`

Associated Rails commit is here: https://github.com/rails/rails/commit/37bef5827f94137f4542cacc669e9c3ce6c9495d#diff-b9612814175bd0fd6e149934e5c169a7

**Comment by jkowens** [comment]
That's strange, we have a test for synchronize that seems to be working fine with AR 6.0:

https://github.com/zdennis/activerecord-import/blob/64caf253fd6233b75e4152100573c482e8762dd3/test/import_test.rb#L400

I'm not sure why the error message would suggest the `clear_association_cache` method if they're both private. That seems odd to me. In the Rails console can you test the following and let me know what happens:

```
c = Category.new
c.send(:clear_aggregation_cache)
c.send(:clear_association_cache)
```

**Comment by bill-filler** [comment]
The `:clear_association_cache` worked but `:clear_aggregation_cache` did not:
```
Loading development environment (Rails 6.0.0.rc1)
irb: warn: can't alias context from irb_context.
2.6.0 :001 > c = Category.new
Creating scope :active. Overwriting existing method Category.active.
 => #<Category id: nil, name: nil, parent_id: nil, position: nil, source_category_id: nil, created_at: nil, updated_at: nil, workplan_status: "active", parent_type: "Playbook", source_category_type: nil> 
2.6.0 :002 > c.send(:clear_aggregation_cache)
Traceback (most recent call last):
        1: from (irb):2
NoMethodError (undefined method `clear_aggregation_cache' for #<Category:0x000055e7ab379040>)
Did you mean?  clear_association_cache
2.6.0 :003 > c.send(:clear_association_cache)
 => nil 
```

**Comment by jkowens** [comment]
Thanks. I wonder why one is found but not the other. I’ll have to look into this more later.

**Comment by mjfrey** [comment]
I think the issue is the following PR that was merged.  ActiveRecord no longer includes Aggregations but rather extends the class methods:

https://github.com/rails/rails/commit/657060b5f8c14fc6249fc19231f703a7c749d84e#diff-391caa9b9464021e932ebf657fa9b13c

**Comment by jkowens** [comment]
Ah ok. I believe the code for synchronize avoids `reload` because it executes a database query for each record. Currently it only executes 1 query.

**Comment by jkowens** [comment]
Thanks @bill-filler and @mjfrey. I think I got a fix worked out. If you can test the code in `master` and let me know for sure that would be awesome.

**Comment by mjfrey** [comment]
Thanks @jkowens this works.  Are you going to tag a release?

**Comment by bill-filler** [comment]
@jkowens 
just tried it and it works. thanks for your help!

**Comment by jkowens** [comment]
Great, I'll try to get a release out soon.

**Comment by jkowens** [comment]
This fix has just been released in v1.0.2 🚀
