### ISSUE TITLE
Oracle error - undefined method `add_column_for_on_duplicate_key_update' for #<ActiveRecord::ConnectionAdapters::OracleEnhancedAdapter:0x000055e27851b020> 

### ISSUE THREAD

**Issue by dsobiera** [zdennis/activerecord-import#695]
Using activerecord-oracle_enhanced-adapter 5.2.8

Active-record-import 1.0.3 works fine. But for both 1.0.4 and 1.0.5 on an import I get:

undefined method `add_column_for_on_duplicate_key_update' for #<ActiveRecord::ConnectionAdapters::OracleEnhancedAdapter:0x000055e27851b020> 

Any ideas why this works in 1.0.3 but 1.0.4 and 1.0.5 it fails?

**Comment by jkowens** [comment]
What ActiveRecord and Ruby version are you using?

**Comment by dsobiera** [comment]
Ruby - 2.6.5
ActiveRecord - 5.2.4.3

**Comment by jkowens** [comment]
Are you using this gem for oracle support?

https://github.com/keeguon/activerecord-import-oracle_enhanced

In v1.0.4 #648 was released. I wonder if that requires an update for `activerecord-import-oracle_enhanced`?

**Comment by dsobiera** [comment]
Although I am using activerecord-oracle_enhanced-adapter I am not using  activerecord-import-oracle_enhanced.

Just the oracle enhanced adapter and plain activerecord-import.


activerecord-oracle_enhanced-adapter (5.2.8)

**Comment by jkowens** [comment]
I'm not sure how you're getting that to work. AR-Import only supports sqlite, mysql, and postgres on its own. Did you create your own adapter?

**Comment by dsobiera** [comment]
No.

I don't know how it is working.  /shrug

But it appears to when using 1.0.3.  This was set up by a previous developer and is inherited legacy that I'm being asked to support now. I was asked to update depedencies and when I did it went boom

**Comment by jkowens** [comment]
I found the issue, I'll try to cut a new release this weekend 👍

**Comment by jkowens** [comment]
Version 1.0.6 has been released. Let me know if you still have an issue, thanks.

**Comment by dsobiera** [comment]
That seemed to fix it. The code runs fine, no error and does what it should.

Thank you!!
