### PR TITLE
Ensure @attribute_cache is cleared in Rails4.0 or lower

### PR DESCRIPTION
**Pull request by yuroyoro**
Backwards compatibility of `synchronize` for Rails4.0 has been broken 
since d18c332c7c35b663012697cbe0060fd60d27a860 was committed.

In Rails4.0, ActiveRecord doesn't have `clear_changes_information` method, 
but clearing `changed_attributes` isn't sufficient to refresh AR object's attribute.
It is necessary to clearing the `@attribute_cache` also.

### CODE REVIEW

**Comment by yuroyoro** [comment]
Travis test `rake test:em_mysql2` failed. But I don't know how to fix this.
On master brach, test also fails with same reason.

```
Running: AR_VERSION=3.1 run bundle exec rake test:em_mysql2
Running: AR_VERSION=3.1 bundle exec rake test:em_mysql2
-- create_table(:schema_info, {:force=>true})
   -> 0.0096s
/home/travis/build/zdennis/activerecord-import/vendor/bundle/ruby/2.0.0/gems/em-synchrony-1.0.4/lib/em-synchrony/activerecord.rb:71:in `current_transaction': undefined method `[]' for nil:NilClass (NoMethodError)
	from /home/travis/build/zdennis/activerecord-import/vendor/bundle/ruby/2.0.0/gems/em-synchrony-1.0.4/lib/em-synchrony/activerecord.rb:98:in `add_transaction_record'
	from /home/travis/build/zdennis/activerecord-import/vendor/bundle/ruby/2.0.0/gems/activerecord-3.1.12/lib/active_record/transactions.rb:280:in `add_to_transaction'
```

**Comment by johnnaegle** [comment]
Try pinning the em-synchrony version to 1.0.3

See https://github.com/igrigorik/em-synchrony/issues/189

**Comment by johnnaegle** [comment]
Failing tests might be fixed by #180

**Comment by zdennis** [comment]
Failing tests resolved with removal of `em-synchrony` in PR #239.

@yuroyoro, any idea how you came across this issue so we can add a test? In the original issue description I think you referenced your latest commit instead of the commit that introduced the problem. 

Thanks,

**Comment by zdennis** [comment]
Thanks @yuroyoro this has been fixed in commit 259e8409dd3b0fd9fba0b9594bfebe611ef0246a . Closing this PR.
