### ISSUE TITLE
undefined local variable or method `sqlite_version' for Rails 6.0.0.rc1+

### ISSUE THREAD

**Issue by madeindjs** [zdennis/activerecord-import#618]
I have this bug since I upgraded to Rails 6.0.0.rc1 :

~~~
NameError: undefined local variable or method `sqlite_version' for #<ActiveRecord::ConnectionAdapters::SQLite3Adapter:0x000055f1cae7f8a8>
/home/arousseau/.rvm/gems/ruby-2.6.0/gems/activerecord-import-1.0.1/lib/activerecord-import/adapters/sqlite3_adapter.rb:20:in `supports_on_duplicate_key_update?'
/home/arousseau/.rvm/gems/ruby-2.6.0/gems/activerecord-import-1.0.1/lib/activerecord-import/adapters/sqlite3_adapter.rb:52:in `pre_sql_statements'
/home/arousseau/.rvm/gems/ruby-2.6.0/gems/activerecord-import-1.0.1/lib/activerecord-import/import.rb:789:in `import_without_validations_or_callbacks'
/home/arousseau/.rvm/gems/ruby-2.6.0/gems/activerecord-import-1.0.1/lib/activerecord-import/import.rb:750:in `import_with_validations'
/home/arousseau/.rvm/gems/ruby-2.6.0/gems/activerecord-import-1.0.1/lib/activerecord-import/import.rb:692:in `import_helper'
/home/arousseau/.rvm/gems/ruby-2.6.0/gems/activerecord-import-1.0.1/lib/activerecord-import/import.rb:526:in `bulk_import'
~~~

`sqlite_version` usage was introduced by https://github.com/zdennis/activerecord-import/commit/816ce64078d7b4b66c8d272073e905b748207693 .

So I look at Active Record code and it seem that [`sqlite_version` methods exists in 5.2](https://github.com/rails/rails/blob/v5.2.2/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb#L490) but was replaced by `get_database_version` on [this commit](https://github.com/rails/rails/commit/1c6e508ade793b5f2676e9218ab2f4cc9474f9ce#diff-2839328ceb6b7f07463747f2ac0dabf3R400).

So I think we should replace `sqlite_version` for Rails 6.0.0.rc1+ versions.

**Comment by jkowens** [comment]
Thanks for the report!

**Comment by madeindjs** [comment]
What reactivity! Thank you.

**Comment by jkowens** [comment]
This fix has just been released in v1.0.2 🚀
